#!/usr/bin/env python3
"""
Generate Style Rules
Creates a .style-rules.json file from detected style patterns.
"""

import json
import sys
from pathlib import Path
from detect_style import detect_project_style


def generate_rules(detection: dict) -> dict:
    """Generate rules from style detection results."""
    rules = {}
    
    # Python rules
    if 'python' in detection:
        py = detection['python']
        rules['python'] = {
            'line_length': 100 if py.get('line_length', {}).get('over_100', 0) == 0 else 120,
            'indentation': py.get('indentation', '4-space'),
            'quotes': py.get('quotes', 'double'),
            'naming': py.get('naming', {
                'functions': 'snake_case',
                'classes': 'PascalCase',
                'constants': 'SCREAMING_SNAKE_CASE',
            }),
            'require_docstrings': py.get('docstrings', {}).get('coverage_percent', 0) > 70,
            'require_type_hints': py.get('type_hints', {}).get('usage_percent', 0) > 70,
            'docstring_style': py.get('docstrings', {}).get('style', 'google'),
            'string_formatting': py.get('string_formatting', 'f-string'),
            'trailing_commas': py.get('trailing_commas', 'no') == 'yes',
        }
    
    # JavaScript rules
    if 'javascript' in detection:
        js = detection['javascript']
        rules['javascript'] = {
            'line_length': 100 if js.get('line_length', {}).get('max', 0) <= 100 else 120,
            'indentation': js.get('indentation', '2-space'),
            'quotes': js.get('quotes', 'single'),
            'semicolons': js.get('semicolons', 'yes'),
            'variable_declaration': js.get('variable_declaration', 'const'),
            'function_style': js.get('function_style', 'arrow'),
            'trailing_commas': js.get('trailing_commas', 'no') == 'yes',
            'naming': js.get('naming', {
                'functions': 'camelCase',
                'classes': 'PascalCase',
                'constants': 'SCREAMING_SNAKE_CASE',
                'variables': 'camelCase',
            }),
        }
    
    return rules


def generate_eslint_config(rules: dict) -> dict:
    """Generate .eslintrc.json from rules."""
    js_rules = rules.get('javascript', {})
    
    eslint = {
        'env': {
            'browser': True,
            'es2021': True,
            'node': True,
        },
        'extends': ['eslint:recommended'],
        'parserOptions': {
            'ecmaVersion': 'latest',
            'sourceType': 'module',
        },
        'rules': {}
    }
    
    # Quote style
    quote = js_rules.get('quotes', 'single')
    eslint['rules']['quotes'] = ['warn', quote]
    
    # Semicolons
    semi = js_rules.get('semicolons', 'yes')
    eslint['rules']['semi'] = ['warn', 'always' if semi == 'yes' else 'never']
    
    # Indentation
    indent = js_rules.get('indentation', '2-space')
    if indent == 'tab':
        eslint['rules']['indent'] = ['warn', 'tab']
    else:
        spaces = int(indent.split('-')[0])
        eslint['rules']['indent'] = ['warn', spaces]
    
    # No var
    if js_rules.get('variable_declaration') in ('const', 'let'):
        eslint['rules']['no-var'] = 'warn'
        eslint['rules']['prefer-const'] = 'warn'
    
    # Line length
    max_len = js_rules.get('line_length', 100)
    eslint['rules']['max-len'] = ['warn', {'code': max_len}]
    
    # Trailing commas
    if js_rules.get('trailing_commas'):
        eslint['rules']['comma-dangle'] = ['warn', 'always-multiline']
    
    # Arrow functions
    if js_rules.get('function_style') == 'arrow':
        eslint['rules']['prefer-arrow-callback'] = 'warn'
    
    return eslint


def generate_ruff_config(rules: dict) -> str:
    """Generate ruff.toml from rules."""
    py_rules = rules.get('python', {})
    
    lines = ['# Generated by code-style skill', '[tool.ruff]']
    
    # Line length
    lines.append(f"line-length = {py_rules.get('line_length', 100)}")
    
    # Target Python version
    lines.append('target-version = "py310"')
    
    lines.append('')
    lines.append('[tool.ruff.lint]')
    
    # Select rules
    select = ['E', 'F', 'W']  # Base pycodestyle and pyflakes
    
    if py_rules.get('require_docstrings'):
        select.append('D')  # pydocstyle
    
    if py_rules.get('require_type_hints'):
        select.append('ANN')  # flake8-annotations
    
    lines.append(f"select = {json.dumps(select)}")
    
    # Quote style
    lines.append('')
    lines.append('[tool.ruff.lint.flake8-quotes]')
    quote = py_rules.get('quotes', 'double')
    lines.append(f'inline-quotes = "{quote}"')
    
    # Docstring style
    if py_rules.get('require_docstrings'):
        lines.append('')
        lines.append('[tool.ruff.lint.pydocstyle]')
        style = py_rules.get('docstring_style', 'google')
        lines.append(f'convention = "{style}"')
    
    return '\n'.join(lines)


def main():
    if len(sys.argv) < 2:
        print("Usage: generate_rules.py <project_path> [--output .style-rules.json]", file=sys.stderr)
        print("       generate_rules.py <detection.json> --from-detection [--output .style-rules.json]", file=sys.stderr)
        print("       --eslint  Also generate .eslintrc.json", file=sys.stderr)
        print("       --ruff    Also generate ruff.toml", file=sys.stderr)
        sys.exit(1)
    
    input_path = sys.argv[1]
    output_file = '.style-rules.json'
    from_detection = '--from-detection' in sys.argv
    gen_eslint = '--eslint' in sys.argv
    gen_ruff = '--ruff' in sys.argv
    
    if '--output' in sys.argv:
        output_file = sys.argv[sys.argv.index('--output') + 1]
    
    # Get detection results
    if from_detection:
        with open(input_path) as f:
            detection = json.load(f)
    else:
        print(f"Detecting style in {input_path}...")
        detection = detect_project_style(input_path)
    
    # Generate rules
    rules = generate_rules(detection)
    
    # Write main rules file
    output_path = Path(output_file)
    with open(output_path, 'w') as f:
        json.dump(rules, f, indent=2)
    print(f"✅ Generated {output_path}")
    
    # Generate ESLint config
    if gen_eslint and 'javascript' in rules:
        eslint = generate_eslint_config(rules)
        eslint_path = output_path.parent / '.eslintrc.json'
        with open(eslint_path, 'w') as f:
            json.dump(eslint, f, indent=2)
        print(f"✅ Generated {eslint_path}")
    
    # Generate Ruff config
    if gen_ruff and 'python' in rules:
        ruff = generate_ruff_config(rules)
        ruff_path = output_path.parent / 'ruff.toml'
        with open(ruff_path, 'w') as f:
            f.write(ruff)
        print(f"✅ Generated {ruff_path}")
    
    # Print summary
    print("\nDetected conventions:")
    if 'python' in rules:
        py = rules['python']
        print(f"  Python:")
        print(f"    - Indentation: {py.get('indentation')}")
        print(f"    - Naming: functions={py['naming'].get('functions')}, classes={py['naming'].get('classes')}")
        print(f"    - Docstrings: {'required' if py.get('require_docstrings') else 'optional'}")
        print(f"    - Type hints: {'required' if py.get('require_type_hints') else 'optional'}")
    
    if 'javascript' in rules:
        js = rules['javascript']
        print(f"  JavaScript:")
        print(f"    - Quotes: {js.get('quotes')}")
        print(f"    - Semicolons: {js.get('semicolons')}")
        print(f"    - Variables: prefer {js.get('variable_declaration')}")
        print(f"    - Functions: prefer {js.get('function_style')}")


if __name__ == "__main__":
    main()
