"""SYERP service layer (business logic).


Split into cohesive submodules (chore-syerp-service-split); this package
re-exports the full public surface so `from app.modules.syerp.service import X`
and `service.X` keep working unchanged.
"""
from __future__ import annotations

from app.modules.syerp.service._common import (
    _COST_QUANTUM,
)
from app.modules.syerp.service.accounts import (
    _gl_account_id_by_code,
    list_gl_accounts,
)
from app.modules.syerp.service.partners import (
    _build_partner_kwargs,
    archive_partner,
    create_partner,
    generate_partner_code,
    get_partner,
    list_partners,
    update_partner,
)
from app.modules.syerp.service.locations import (
    create_location,
    get_location,
    list_locations,
    update_location,
)
from app.modules.syerp.service.items import (
    _ITEM_CODE_RE,
    _build_item_kwargs,
    _next_item_code,
    _validate_plum_part,
    create_item,
    generate_item_code,
    get_item,
    list_items,
    update_item,
)
from app.modules.syerp.service.inventory import (
    _adjustment_violates_floor,
    _derive_onhand,
    compute_new_moving_avg,
    get_bin_on_hand,
    get_item_on_hand,
    get_item_onhand,
    list_item_transactions,
    post_adjustment,
    post_issue,
    post_putaway,
    post_receipt,
    post_transfer,
)
from app.modules.syerp.service.journal import (
    _get_journal_entry_row,
    _je_account_id,
    _je_is_balanced,
    _je_side,
    _je_to_read,
    _je_totals,
    _load_journal_lines,
    _require_gl_account,
    _reverse_lines,
    derive_account_balance,
    get_account_register,
    get_journal_entry,
    latest_journal_entry_id_for_source,
    list_journal_entries,
    post_journal_entry,
    reverse_journal_entry,
)
from app.modules.syerp.service.purchasing import (
    PO_TRANSITIONS,
    _POAggregates,
    _PO_NUMBER_RE,
    _get_line_row,
    _get_po_row,
    _is_over_receipt,
    _load_po_lines,
    _next_line_no,
    _next_po_number,
    _po_aggregates,
    _po_rollup_status,
    _po_to_read,
    _require_draft,
    add_line,
    advance_po_status,
    create_po,
    generate_po_number,
    get_po,
    list_pos,
    receive_line,
    remove_line,
    update_line,
)
from app.modules.syerp.service.bills import (
    BILL_TRANSITIONS,
    _BILL_NUMBER_RE,
    _PreparedBillLine,
    _already_billed_qty,
    _bill_paid_amount,
    _bill_to_read,
    _bill_transition_allowed,
    _get_bill_row,
    _is_exact_match,
    _is_overpayment,
    _load_bill_lines,
    _next_bill_number,
    _unbilled_qty,
    advance_bill_status,
    create_bill,
    generate_bill_number,
    get_bill,
    list_bills,
    list_payments,
    list_unbilled_receipts,
    post_bill,
    record_payment,
)
from app.modules.syerp.service.ar import (
    INVOICE_TRANSITIONS,
    _INVOICE_NUMBER_RE,
    _PreparedInvoiceLine,
    _get_invoice_row,
    _invoice_received_amount,
    _invoice_to_read,
    _invoice_transition_allowed,
    _load_invoice_lines,
    _next_invoice_number,
    _uninvoiced_qty,
    create_invoice,
    generate_invoice_number,
    get_invoice,
    list_invoices,
    list_uninvoiced_shipments,
    post_invoice,
)
from app.modules.syerp.service.reports import (
    ap_aging_report,
    balance_sheet,
    profit_loss,
    trial_balance,
)

__all__ = [
    "BILL_TRANSITIONS",
    "INVOICE_TRANSITIONS",
    "PO_TRANSITIONS",
    "add_line",
    "advance_bill_status",
    "advance_po_status",
    "ap_aging_report",
    "archive_partner",
    "balance_sheet",
    "compute_new_moving_avg",
    "create_bill",
    "create_invoice",
    "create_item",
    "create_location",
    "create_partner",
    "create_po",
    "derive_account_balance",
    "generate_bill_number",
    "generate_invoice_number",
    "generate_item_code",
    "generate_partner_code",
    "generate_po_number",
    "get_account_register",
    "get_bill",
    "get_bin_on_hand",
    "get_invoice",
    "get_item",
    "get_item_on_hand",
    "get_item_onhand",
    "get_journal_entry",
    "get_location",
    "get_partner",
    "get_po",
    "latest_journal_entry_id_for_source",
    "list_bills",
    "list_invoices",
    "list_gl_accounts",
    "list_item_transactions",
    "list_items",
    "list_journal_entries",
    "list_locations",
    "list_partners",
    "list_payments",
    "list_pos",
    "list_unbilled_receipts",
    "list_uninvoiced_shipments",
    "post_adjustment",
    "post_bill",
    "post_invoice",
    "post_issue",
    "post_journal_entry",
    "post_putaway",
    "post_receipt",
    "post_transfer",
    "profit_loss",
    "receive_line",
    "record_payment",
    "remove_line",
    "reverse_journal_entry",
    "trial_balance",
    "update_item",
    "update_line",
    "update_location",
    "update_partner",
]
